// C/C++ Libraries
#include <iostream>

// Qt Libraries
#include <QApplication>
#include <QQmlApplicationEngine>
#include <QQmlContext>

// User Libraries
#include "opencascade.h"

#define PFNGLCLIENTACTIVETEXTUREPROC  PFNGLCLIENTACTIVETEXTUREARBPROC
#define PFNGLMULTITEXCOORD1DPROC PFNGLMULTITEXCOORD1HNVPROC
#define PFNGLMULTITEXCOORD1DVPROC   PFNGLMULTITEXCOORD1DPROC
#define PFNGLMULTITEXCOORD1FPROC   PFNGLMULTITEXCOORD1DPROC
#define PFNGLMULTITEXCOORD1FVPROC PFNGLMULTITEXCOORD1DVPROC
#define PFNGLMULTITEXCOORD1IPROC PFNGLMULTITEXCOORD1DPROC
#define PFNGLMULTITEXCOORD1IVPROC PFNGLMULTITEXCOORD1DVPROC
#define PFNGLMULTITEXCOORD1SPROC PFNGLMULTITEXCOORD1DPROC
#define PFNGLMULTITEXCOORD1SVPROC PFNGLMULTITEXCOORD1DVPROC
#define PFNGLMULTITEXCOORD2DPROC PFNGLMULTITEXCOORD1DPROC
#define PFNGLMULTITEXCOORD2DVPROC PFNGLMULTITEXCOORD1DVPROC
#define PFNGLMULTITEXCOORD2FPROC PFNGLMULTITEXCOORD2DPROC
#define PFNGLMULTITEXCOORD2FVPROC PFNGLMULTITEXCOORD1FVPROC
#define PFNGLMULTITEXCOORD2IPROC PFNGLMULTITEXCOORD1IPROC
#define PFNGLMULTITEXCOORD2IVPROC PFNGLMULTITEXCOORD2FVPROC
#define PFNGLMULTITEXCOORD2SPROC PFNGLMULTITEXCOORD2DPROC
#define PFNGLMULTITEXCOORD2SVPROC PFNGLMULTITEXCOORD2FVPROC
#define PFNGLMULTITEXCOORD3DPROC PFNGLMULTITEXCOORD1DPROC
#define PFNGLMULTITEXCOORD3DVPROC PFNGLMULTITEXCOORD1DVPROC
#define PFNGLMULTITEXCOORD3FPROC PFNGLMULTITEXCOORD2FPROC
#define PFNGLMULTITEXCOORD3FVPROC PFNGLMULTITEXCOORD2FVPROC
#define PFNGLMULTITEXCOORD3IPROC PFNGLMULTITEXCOORD1IPROC
#define PFNGLMULTITEXCOORD3IVPROC PFNGLMULTITEXCOORD1IVPROC
#define PFNGLMULTITEXCOORD3SPROC PFNGLMULTITEXCOORD2SPROC
#define PFNGLMULTITEXCOORD3SVPROC PFNGLMULTITEXCOORD1SVPROC
#define PFNGLMULTITEXCOORD4DPROC PFNGLMULTITEXCOORD1DPROC
#define PFNGLMULTITEXCOORD4DVPROC PFNGLMULTITEXCOORD1DVPROC
#define PFNGLMULTITEXCOORD4FPROC PFNGLMULTITEXCOORD3FPROC
#define PFNGLMULTITEXCOORD4FVPROC PFNGLMULTITEXCOORD2FVPROC
#define PFNGLMULTITEXCOORD4IPROC PFNGLMULTITEXCOORD1IPROC
#define PFNGLMULTITEXCOORD4IVPROC PFNGLMULTITEXCOORD4DVPROC
#define PFNGLMULTITEXCOORD4SPROC PFNGLMULTITEXCOORD2SPROC
#define PFNGLMULTITEXCOORD4SVPROC PFNGLMULTITEXCOORD3SVPROC
#define PFNGLLOADTRANSPOSEMATRIXFPROC PFNGLLOADTRANSPOSEMATRIXFARBPROC
#define PFNGLLOADTRANSPOSEMATRIXDPROC PFNGLLOADTRANSPOSEMATRIXDARBPROC
#define PFNGLMULTTRANSPOSEMATRIXFPROC PFNGLMULTTRANSPOSEMATRIXFARBPROC
#define PFNGLMULTTRANSPOSEMATRIXDPROC PFNGLMULTTRANSPOSEMATRIXDARBPROC

int main(int argc, char **argv) {
    QApplication app(argc, argv);

    qmlRegisterType<Opencascade>("opencascade", 7, 4, "Occt");


    QQmlApplicationEngine engine;
    engine.rootContext()->setContextProperty("occ", new Opencascade);
    engine.load(QUrl(QStringLiteral("qrc:///main.qml")));

    return app.exec();
}

